package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import javafx.scene.control.PasswordField;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.DatePicker;

public class PaymentController implements Initializable{
	private Stage stage;
	private Scene scene;
	private Parent root;
	private double x;
	private double y;
	
    @FXML
    private Label totalBill;
	@FXML
	private Label fullName;
	@FXML
	private ImageView userImg;
	@FXML
	private TextField firstName;
	@FXML
	private TextField accountNum;
	@FXML
	private TextField lastName;
	@FXML
	private PasswordField cvv;
	@FXML
	private DatePicker date;

	// Event Listener on Button.onAction
	@FXML
	public void goToHome(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		SingletonCookie sc = SingletonCookie.getInstace(null, -1, null);
		fullName.setText(sc.getUserName());
		
		InputStream stream = null;
		try {
			stream = new FileInputStream(sc.getImagePath());
		    Image image = new Image(stream);
		    userImg.setImage(image);
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		PersistenceFactory pf = PersistenceFactory.getInstace(null);

		try {
			totalBill.setText(""+pf.getDB().getTotalBill()+" Rs-/");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}	
	
	// Event Listener on Button.onAction
	@FXML
	public void goToBookMovie(ActionEvent event) throws IOException
	{
		root = FXMLLoader.load(getClass().getResource("BookMovie.fxml"));
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.getIcons().add(new Image("./Images/logo.png"));
		stage.setTitle("Book Movie");
		stage.show();
		
		root.setOnMousePressed((MouseEvent Mevent) -> {
			x = Mevent.getSceneX();
			y = Mevent.getSceneY();
		});
		
		root.setOnMouseDragged((MouseEvent Mevent) ->{
			stage.setX(Mevent.getScreenX() - x);
			stage.setY(Mevent.getScreenY() - y);
		});
	}
	// Event Listener on Button.onAction
	@FXML
	public void goToLogin(ActionEvent event) throws IOException, SQLException {
		root = FXMLLoader.load(getClass().getResource("Login.fxml"));
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.getIcons().add(new Image("./Images/logo.png"));
		stage.setTitle("Login");
		stage.show();
		
		root.setOnMousePressed((MouseEvent Mevent) -> {
			x = Mevent.getSceneX();
			y = Mevent.getSceneY();
		});
		
		root.setOnMouseDragged((MouseEvent Mevent) ->{
			stage.setX(Mevent.getScreenX() - x);
			stage.setY(Mevent.getScreenY() - y);
		});
		SingletonCookie sc = SingletonCookie.getInstace("", -1, "");
		sc.cleanUserSession();
	}
	// Event Listener on Button.onAction
	@FXML
	public void makePayment(ActionEvent event) throws IOException, SQLException {
		boolean success = Cinema.getInstace(null,null,null,null).makePayment(firstName.getText(),lastName.getText(), accountNum.getText(),cvv.getText());
		if(success == true) {
			root = FXMLLoader.load(getClass().getResource("BookMovie.fxml"));
			stage = (Stage)((Node)event.getSource()).getScene().getWindow();
			scene = new Scene(root);
			stage.setScene(scene);
			stage.getIcons().add(new Image("./Images/logo.png"));
			stage.setTitle("Payment");
			stage.show();
			
			root.setOnMousePressed((MouseEvent Mevent) -> {
				x = Mevent.getSceneX();
				y = Mevent.getSceneY();
			});
			
			root.setOnMouseDragged((MouseEvent Mevent) ->{
				stage.setX(Mevent.getScreenX() - x);
				stage.setY(Mevent.getScreenY() - y);
			});
		}		
	}
	
	@FXML
	public void delBooking(ActionEvent event) throws IOException, SQLException {
		Booking booking = new Booking();
		boolean success = booking.removeBooking(firstName.getText(),lastName.getText(), accountNum.getText(),cvv.getText());
		root = FXMLLoader.load(getClass().getResource("BookMovie.fxml"));
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.getIcons().add(new Image("./Images/logo.png"));
		stage.setTitle("Payment");
		stage.show();
			
		root.setOnMousePressed((MouseEvent Mevent) -> {
			x = Mevent.getSceneX();
			y = Mevent.getSceneY();
		});
			
		root.setOnMouseDragged((MouseEvent Mevent) ->{
			stage.setX(Mevent.getScreenX() - x);
			stage.setY(Mevent.getScreenY() - y);
		});	
	}
}
